name: Creative
author: MCMagicDev
version: 1.9.1
depend: [MCMagicCore, ProtocolLib, PlotSquared]
description: MCMagic Creative Server Plugin
main: us.mcmagic.creative.Creative
commands:
   vanish:
      description: Hides you from the Guests!
      permission: vanish.standard
      permission-message: §4You don’t have permission for this command
      aliases: v
   head:
      description: Reload Head Database
      permission: arcade.bypass
      permission-message: §4You don’t have permission for this command
   bc:
      description: Broadcast to the whole server
      permission: mcmagic.bc
      permission-message: §4You don’t have permission for this command
   pt:
      description: Set your Particle!
      permission: mcmagic.warp
      permission-message: §4You don’t have permission for this command
   star:
      description: Get the Creative Menu!
      permission: mcmagic.warp
      permission-message: §4You don’t have permission for this command
   role:
      description: Manage your Role Play!
      permission: mcmagic.warp
      permission-message: §4You don’t have permission for this command
      aliases: [roleplay]
   creator:
      description: The Creator Project commands
      permission: mcmagic.warp
      permission-message: §4You don’t have permission for this command
   show:
      description: Edit your Show!
      permission: mcmagic.warp
      permission-message: §4You don’t have permission for this command
   rules:
      description: Creative Rules
      permission: mcmagic.warp
      permission-message: §4You don’t have permission for this command
      aliases: [roleplay]
   shop:
      description: Visit the Creative Shop
      permission: mcmagic.warp
      permission-message: §4You don’t have permission for this command
      aliases: [roleplay]
   manage:
      description: mcmagic.tp
      permission: mcmagic.bc
      permission-message: §4You don’t have permission for this command
   more:
      description: Gets 64 of the item in your hand!
      permission: mcmagic.more
      permission-message: §4You don’t have permission for this command
   msg:
      description: You can't use this! :P
      permission: mcmagic.msg
      permission-message: §4You don’t have permission for this command
      aliases: [tell, whisper]
   banner:
      description: Banner Menu!
      permission: mcmagic.banner
      permission-message: §4You don’t have permission for this command
   music:
      description: Play a record for your Plot
      permission: mcmagic.banner
      permission-message: §4You don’t have permission for this command
   tp:
      description: Teleport!
      permission: mcmagic.tp
      permission-message: §4You don’t have permission for this command
      aliases: tppos
   tpa:
      description: Send a Teleport Request!
      permission: creative.tpa
      permission-message: §4You don’t have permission for this command
   menu:
      description: Default menu command
      permission: creative.tpa
      permission-message: §4You don’t have permission for this command
   tpaccept:
      description: Accept a Teleport Request!
      permission: creative.tpa
      permission-message: §4You don’t have permission for this command
   tpdeny:
      description: Deny a Teleport Request!
      permission: creative.tpa
      permission-message: §4You don’t have permission for this command
   spawn:
      description: Teleport you to spawn!
      permission: creative.tpa
      permission-message: §4Please tell a Staff Member you can't use this command!
   setspawn:
      description: Set the spawn location!
      permission: vanish.standard
      permission-message: §4You don’t have permission for this command
   ptime:
      description: Set the time for a player!
      permission: mcmagic.ptime
      permission-message: §4You don’t have permission for this command
   pweather:
      description: Set the weather for a player!
      permission: mcmagic.pweather
      permission-message: §4You don’t have permission for this command
   warp:
      description: Teleport to a Warp!
      permission: mcmagic.warp
      permission-message: §4Please tell a Staff Member you can't use this command!
   setwarp:
      description: Set a Warp!
      permission: mcmagic.setwarp
      permission-message: §4You don’t have permission for this command
   delwarp:
      description: Delete a Warp!
      permission: mcmagic.delwarp
      permission-message: §4You don’t have permission for this command
   helpop:
      description: Chat online staff members
      permission: mcmagic.bc
      permission-message: §4You don’t have permission for this command
      aliases: ac
   give:
      description: Give yourself an item!
      permission: mcmagic.give
      permission-message: §4You don’t have permission for this command
      aliases: [item, i]
   heal:
      description: Heal a specified player
      permission: arcade.bypass
      permission-message: §4You don’t have permission for this command
   invsee:
      description: View the inventory of another player
      permission: arcade.bypass
      permission-message: §4You don’t have permission for this command
   back:
      description: Teleport to last location
      permission: vanish.standard
      permission-message: §4You don’t have permission for this command
   loglag:
      description: Spam your chat with fun stuff
      permission: arcade.bypass
      permission-message: §4You don’t have permission for this command
   nv:
      description: Give/take NightVision
      permission: creative.tpa
      permission-message: §4Please tell a Staff Member you can't use this command!